apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-persistent-claim
  namespace: jagadishkl
spec:
  volumeMode: Filesystem
  storageClassName: pv-jagadishkl
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi