apiVersion: v1
kind: Service
metadata:
  labels:
    app: business
  name: business
  namespace: jagadishkl
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: business
  type: NodePort
status:
  loadBalancer: {}
