apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: jagadishkl
spec:
  storageClassName: mysql-jagadishkl
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
